import type { MetadataRoute } from "next";

const routes = [
  "",
  "/about",
  "/personal",
  "/business",
  "/commercial",
  "/institutional",
  "/wealth",
  "/advice",
  "/accounts",
  "/pricing",
  "/security",
  "/help",
  "/contact",
  "/terms",
  "/privacy",
  "/risk-disclosure",
  "/login",
  "/register",
  "/forgot-password",
  "/reset-password",
  "/verify-email",
  "/phone-otp",
  "/two-factor",
  "/two-factor-setup",
  "/dashboard",
  "/kyc",
  "/kyc/status",
  "/kyc/approved",
  "/kyc/rejected",
  "/wallets",
  "/wallets/btc",
  "/deposit",
  "/deposit/success",
  "/withdraw",
  "/withdraw/status",
  "/withdraw/WDR-2204",
  "/portfolio",
  "/transactions",
  "/transactions/TXN-90841",
  "/notifications",
  "/notifications/preferences",
  "/support",
  "/support/tickets",
  "/support/tickets/SUP-1402",
  "/statements",
  "/statements/may-2026",
  "/price-alerts",
  "/referral",
  "/settings",
  "/settings/security",
  "/settings/devices",
  "/account-restricted",
  "/maintenance",
  "/ui-completion",
];

export default function sitemap(): MetadataRoute.Sitemap {
  return routes.map((route) => ({
    url: `https://northunion.example${route}`,
    lastModified: new Date("2026-05-13"),
    changeFrequency: "weekly",
    priority: route === "" ? 1 : 0.7,
  }));
}
